#Assignment Upload Metadata
#Sun Sep 06 19:56:39 IST 2026
week.1.filename=java1.pdf
week.1.sizeBytes=596
week.1.uploadedAt=2026-09-06 19\:56\:22
week.12.filename=java12.pdf
week.12.sizeBytes=596
week.12.uploadedAt=2026-09-06 19\:56\:39
